#!/bin/sh
# This script is designed to be executed per user.

# install rust per user, kind of annoying but the only supported method of obtaining rust 1.31+ for actix support. rocket is even worse and requires the unstable rust branch...  
curl https://sh.rustup.rs -sSf | sh -s -- -y

