#!/bin/sh
# This script is designed to be run once per machine as root(use sudo).

echo "installing packages"
apt install make git build-essential gdbserver libudev-dev postgresql postgresql-contrib postgresql-client

# super secure! note: this does not modify the postgres linux user password.
sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"


