#!/bin/sh
# This script is designed to be run once per machine as root(use sudo).

if getent passwd postgres > /dev/null 2>&1; then
	echo "postgres user already exists, continuing"
else
	echo "creating user postgres, input password for the new user"
	sudo passwd postgres
fi

echo "installing packages"
apt install make git build-essential gdbserver libudev-dev postgresql postgresql-client


