#!/bin/bash
# This script is designed to be executed per user.

# install rust per user, kind of annoying but the only supported method of obtaining rust 1.31+ for actix support. rocket is even worse and requires the unstable rust branch...
curl https://sh.rustup.rs -sSf | sh -s -- -y

mkdir -p ~/.cargo
if [[ -f ./rust_config ]]; then
	cp rust_config ~/.config/
else
	echo "Please rerun this script in the same folder that it is located, ie in the same folder as rust_config"
fi

cargo install cargo-web || echo "failed to install cargo web, this is likely because it is already installed."
